# Generated by Django 3.2.8 on 2021-10-16 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ('title',),
            },
        ),
    ]
